servers=[
  {
    :hostname => "rancher-node1",     
    :ip => "192.168.100.101",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 4096,
    :cpu => 2,
    :scripts => ["install_docker.sh", "install_docker_rancher.sh", "install_kubectl.sh"]
  },
  # {
  #   :hostname => "rancher-node2",     
  #   :ip => "192.168.100.102",
  #   :box => "bento/ubuntu-20.04",
  #   :box_version => "202206.03.0",
  #   :ram => 2048,
  #   :cpu => 2,
  #   :scripts => ["install_docker.sh"]
  # },
  # {
  #   :hostname => "rancher-node3",      
  #   :ip => "192.168.100.103",
  #   :box => "bento/ubuntu-20.04",
  #   :box_version => "202206.03.0",
  #   :ram => 2048,
  #   :cpu => 2,
  #   :scripts => ["install_docker.sh"]
  # }
]

# call Vagrantfile template
eval File.read("./../template/Vagrantfile")
