install_script_path=File.expand_path('../../install-scripts', File.dirname(__FILE__))

servers=[
  {
    :hostname => "node1",     
    :ip => "192.168.100.101",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 4096,
    :cpu => 2,
    :scripts => ["install_docker.sh", "install_docker_rancher.sh", "install_kubectl.sh"]
  },
  # {
  #   :hostname => "node2",     
  #   :ip => "192.168.100.102",
  #   :box => "bento/ubuntu-20.04",
  #   :box_version => "202206.03.0",
  #   :ram => 2048,
  #   :cpu => 2,
  #   :scripts => ["install_docker.sh"]
  # },
  # {
  #   :hostname => "node3",      
  #   :ip => "192.168.100.103",
  #   :box => "bento/ubuntu-20.04",
  #   :box_version => "202206.03.0",
  #   :ram => 2048,
  #   :cpu => 2,
  #   :scripts => ["install_docker.sh"]
  # }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.box_version = machine[:box_version]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            
            # do script
            if machine[:scripts] 
                machine[:scripts].each do |script| 
                    # privileged false -> vagrant, true -> root, default is true
                    node.vm.provision "shell", privileged: false, path: "#{install_script_path}/#{script}"
                end
            end

            node.vm.provider "virtualbox" do |vb|
                vb.name = "K8s-#{machine[:hostname]}"
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]  
            end
        end
    end
end

