install_script_path=File.expand_path('../../install-scripts', File.dirname(__FILE__))

servers=[{
    :hostname => "minikube",     
    :ip => "192.168.100.101",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 4096,
    :cpu => 2,
    :scripts => ["install_docker.sh", "install_minikube.sh", "install_kubectl.sh"]
}]

# call Vagrantfile template
eval File.read("./../template/Vagrantfile")
