servers=[
  {
    :hostname => "k3s-server",
    :ip => "192.168.100.101",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 2048,
    :cpu => 2,
    :scripts => ["install_default_settings.sh", "install_k3s-server.sh"]
  },
  {
    :hostname => "k3s-agent-1",
    :ip => "192.168.100.102",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 1024,
    :cpu => 1,
    :scripts => ["install_default_settings.sh", "install_k3s-agent.sh"]
  }  
]
 
# call Vagrantfile template
eval File.read("./../template/Vagrantfile")