$install_docker_script = <<-SHELL   
  # set version
  export DOCKER_VERSION=5:20.10.17~3-0~ubuntu-focal
  export CONTAINERD_IO_VERSION=1.6.6-1
  export USER=vagrant

  # install docker
  sudo apt-get update
  sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  sudo apt-get update
  sudo apt-get install -y docker-ce=${DOCKER_VERSION} docker-ce-cli=${DOCKER_VERSION} containerd.io=${CONTAINERD_IO_VERSION}
  sudo usermod -aG docker ${USER}
  docker version

  # install other package
  # avoid -bash: _get_comp_words_by_ref: command not found
  sudo apt-get install -y bash-completion
 
  #Disable swap
  #https://github.com/kubernetes/kubernetes/issues/53533
  sudo swapoff -a && sudo sysctl -w vm.swappiness=0
  sudo sed '/vagrant--vg-swap/d' -i /etc/fstab  
SHELL

$install_docker_rancher_script = <<-SHELL
  export WORK_DIR=/home/vagrant
   
  # https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-5-14/
  docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 -v ${WORK_DIR}/rancher:/var/lib/rancher rancher/rancher:v2.5.14
SHELL

$install_kubectl_script = <<-SHELL
  export KUBECTL_VERSION=1.19.13

  sudo apt-get update
  sudo apt-get install -y apt-transport-https ca-certificates curl
  sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  
  sudo apt-get update
  sudo apt-get install -y kubectl=${KUBECTL_VERSION}-00
SHELL

servers=[
  {
    :hostname => "node1",     
    :ip => "192.168.100.101",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 4096,
    :cpu => 2,
    :scripts => [$install_docker_script, $install_docker_rancher_script, $install_kubectl_script]
  },
  {
    :hostname => "node2",     
    :ip => "192.168.100.102",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 1024,
    :cpu => 2,
    :scripts => [$install_docker_script]
  },
  {
    :hostname => "node3",      
    :ip => "192.168.100.103",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 1024,
    :cpu => 2,
    :scripts => [$install_docker_script]
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.box_version = machine[:box_version]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            
            # do script
            if machine[:scripts] 
                machine[:scripts].each do |script| 
                    node.vm.provision "shell", inline: script
                end
            end

            node.vm.provider "virtualbox" do |vb|
                vb.name = "K8s-#{machine[:hostname]}"
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]  
            end
        end
    end
end

