servers=[{
    :hostname => "kubeadm",     
    :ip => "192.168.100.101",
    :box => "bento/ubuntu-20.04",
    :box_version => "202206.03.0",
    :ram => 4096,
    :cpu => 2,
    :scripts => ["install_docker.sh", "install_kubectl.sh", "install_kubeadm.sh"]
}]
 
# call Vagrantfile template
eval File.read("./../template/Vagrantfile")